/* Generated by the program `C:\home\obswteam\workspace\sparc-gcov-master\tools\version\gcov-iov.exe'
   from `4.4 (4 4) and  (*)'.  */
#if ( __GNUC__ == 3 && __GNUC_MINOR__ == 4 )
#define GCOV_VERSION ((gcov_unsigned_t)0x3330342a)  /* type 'gcov-iov 3.4 ""' */
#endif /* __GNUC__ __GNUC_MINOR__ */

#if ( __GNUC__ == 4 && __GNUC_MINOR__ == 4 )
#define GCOV_VERSION ((gcov_unsigned_t)0x3430342a)  /* type 'gcov-iov 4.4 ""' */
#endif /* __GNUC__ __GNUC_MINOR__ */

#if ( __GNUC__  > 4 )
#define GCOV_VERSION ((gcov_unsigned_t)0x3430342a)  /* type 'gcov-iov 4.4 ""' */
#endif /* __GNUC__ __GNUC_MINOR__ */
