CONFIG += console
CONFIG -= qt
QMAKE_CC=sparc-rtems-gcc
message(C compiler forced to: $$QMAKE_CC)
QMAKE_CXX=sparc-rtems-g++
message(C++ compiler forced to: $$QMAKE_CXX)
QMAKE_AR=sparc-rtems-ar rcs
message(Archiver forced to: $$QMAKE_AR)
QMAKE_LINK=sparc-rtems-g++
message(Linker forced to: $$QMAKE_LINK)
QMAKE_LINK_SHLIB=sparc-rtems-g++
QMAKE_OBJCOPY= sparc-rtems-objcopy
QMAKE_STRIP=sparc-rtems-strip
QMAKE_GDB=sparc-rtems-gdb

INCLUDEPATH += /opt/rtems-4.10

QMAKE_CFLAGS_DEBUG= -g
QMAKE_CFLAGS_RELEASE=""
QMAKE_CXXFLAGS_DEBUG= -g
QMAKE_CXXFLAGS_RELEASE=""
QMAKE_LFLAGS_RELEASE=""
QMAKE_LFLAGS_DEBUG= -g
QMAKE_CXXFLAGS_DEPS	=
QMAKE_CXXFLAGS_WARN_ON	= -Wall
QMAKE_CXXFLAGS_WARN_OFF	= -w
QMAKE_CXXFLAGS_RELEASE	=
QMAKE_CXXFLAGS_DEBUG	=
QMAKE_CXXFLAGS_YACC	=
QMAKE_CXXFLAGS_THREAD	=
QMAKE_CXXFLAGS_RTTI_ON	=
QMAKE_CXXFLAGS_RTTI_OFF	=
QMAKE_CXXFLAGS_EXCEPTIONS_ON =
QMAKE_CXXFLAGS_EXCEPTIONS_OFF =
QMAKE_CFLAGS_WARN_ON	= -Wall
QMAKE_CFLAGS_WARN_OFF	= -w
QMAKE_CFLAGS_RELEASE	=
QMAKE_CFLAGS_YACC	=
QMAKE_LFLAGS_EXCEPTIONS_ON =
QMAKE_LFLAGS_EXCEPTIONS_OFF =
QMAKE_LFLAGS_RELEASE	=
QMAKE_LFLAGS_CONSOLE	=
QMAKE_LFLAGS_WINDOWS	=
QMAKE_LFLAGS_DLL        =
QMAKE_INCDIR_QT         =
QMAKE_INCDIR            =
QMAKE_CFLAGS_SHLIB	  =
QMAKE_CFLAGS_STATIC_LIB	  =
QMAKE_CXXFLAGS_SHLIB	  =
QMAKE_CXXFLAGS_STATIC_LIB =
QMAKE_LIBS=""
INCLUDEPATH=""
DEFINES=""

contains( TEMPLATE, app ) {
    OBJECTS_DIR=obj
    DESTDIR=bin
}

QMAKE_CFLAGS_RELEASE+= -O3
QMAKE_CFLAGS_DEBUG+= -O3
QMAKE_CXXFLAGS_RELEASE+= -O3
QMAKE_CXXFLAGS_DEBUG+= -O3
#QMAKE_CFLAGS_RELEASE+= -O3 -std=c99
#QMAKE_CFLAGS_DEBUG+= -O3 -std=c99
#QMAKE_CXXFLAGS_RELEASE+= -O3 -std=c99
#QMAKE_CXXFLAGS_DEBUG+= -O3  -std=c99

contains( TEMPLATE, app ) {
    grmon.target = grmon
    grmon.commands = cd $$DESTDIR && C:/opt/grmon-eval-2.0.29b/win32/bin/grmon.exe -uart COM4 -u
    QMAKE_EXTRA_TARGETS += grmon
}



















