#ifndef TM_BYTE_POSITIONS_H
#define TM_BYTE_POSITIONS_H

// TC_LFR_LOAD_NORMAL_PAR
#define BYTE_POS_SY_LFR_N_CWF_LONG_F3 8

// TM_LFR_HK
#define BYTE_POS_HK_LFR_CPU_LOAD 26
#define BYTE_POS_HK_REACTION_WHEELS_FREQUENCY 135

#endif // TM_BYTE_POSITIONS_H
