#ifndef TM_BYTE_POSITIONS_H
#define TM_BYTE_POSITIONS_H

#define BYTE_POS_CP_LFR_MODE 11

// TC_LFR_LOAD_NORMAL_PAR
#define BYTE_POS_SY_LFR_N_SWF_L 0
#define BYTE_POS_SY_LFR_N_SWF_P 2
#define BYTE_POS_SY_LFR_N_ASM_P 4
#define BYTE_POS_SY_LFR_N_BP_P0 6
#define BYTE_POS_SY_LFR_N_BP_P1 7
#define BYTE_POS_SY_LFR_N_CWF_LONG_F3 8

// TM_LFR_HK
#define BYTE_POS_HK_LFR_CPU_LOAD 26
#define BYTE_POS_HK_REACTION_WHEELS_FREQUENCY 135

#endif // TM_BYTE_POSITIONS_H
