#ifndef TM_BYTE_POSITIONS_H
#define TM_BYTE_POSITIONS_H

// TC_LFR_LOAD_COMMON_PAR

// TC_LFR_LOAD_NORMAL_PAR
#define BYTE_POS_SY_LFR_N_SWF_L 0
#define BYTE_POS_SY_LFR_N_SWF_P 2
#define BYTE_POS_SY_LFR_N_ASM_P 4
#define BYTE_POS_SY_LFR_N_BP_P0 6
#define BYTE_POS_SY_LFR_N_BP_P1 7
#define BYTE_POS_SY_LFR_N_CWF_LONG_F3 8

// TC_LFR_LOAD_BURST_PAR

// TC_LFR_LOAD_SBM1_PAR

// TC_LFR_LOAD_SBM2_PAR

// TC_LFR_UPDATE_INFO
#define BYTE_POS_UPDATE_INFO_PARAMETERS_SET5    34
#define BYTE_POS_UPDATE_INFO_PARAMETERS_SET6    35

// TC_LFR_ENTER_MODE
#define BYTE_POS_CP_MODE_LFR_SET            11
#define BYTE_POS_CP_LFR_ENTER_MODE_TIME     12

#endif // TM_BYTE_POSITIONS_H
